# Supabase + DigitalOcean App Platform deployment
name: striker-splash
services:
  - name: web
    source_dir: /
    github:
      repo: aoideee/striker-splash
      branch: main
    build_command: npm run build
    run_command: npm start
    environment_slug: node-js
    instance_count: 1
    instance_size_slug: basic-xxs
    envs:
      - key: NODE_ENV
        value: production
      # Supabase Database Configuration
      - key: DB_HOST
        value: YOUR_SUPABASE_HOST
      - key: DB_NAME
        value: postgres
      - key: DB_USER
        value: postgres
      - key: DB_PASSWORD
        value: YOUR_SUPABASE_PASSWORD
      - key: DB_PORT
        value: "5432"
      # Application Configuration
      - key: SESSION_SECRET
        value: your_super_secure_production_session_secret_here
      - key: ENABLE_HTTPS
        value: "false"
      - key: TRUST_PROXY
        value: "true"
      - key: ENABLE_DEBUG_LOGGING
        value: "false"
      - key: ENABLE_SENSITIVE_LOGGING
        value: "false"
      - key: LOG_LEVEL
        value: "warn"
    http_port: 3000
# No databases section needed - using external Supabase
